#spring:
#  application:
#    name: authentication

#server:
#  port: 3311
#spring.application.name=authentication
#server.port=3331
##eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/
#from=git-default-1.0
#
#spring.datasource.url=jdbc:mysql://localhost:3306/authentication?useUnicode=true&characterEncoding=utf-8&useSSL=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class=com.mysql.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=update

#spring:
#  application:
#  name: authentication
#server:
# port: 3331
#eureka:
# client:
#  serviceUrl:
#   defaultZone: http://localhost:1111/eureka/

server:
  port: 3331
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
      name: authentication
  datasource:
      url: jdbc:mysql://localhost:3306/authentication?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
from: git-default-1.0