server:
  port: 2222
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: demo-service
  datasource:
    url: jdbc:mysql://localhost:3306/clouddemo?useUnicode=true&characterEncoding=utf-8&useSSL=true
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
