spring:
  application:
    name: gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

zuul:
  routes:
    demo-fegin:
      path: /demo-fegin/**
      serviceId: demo-fegin
      stripPrefix: true
      sensitiveHeaders:
    demo-service:
      path: /demo-service/**
      serviceId: demo-service
      stripPrefix: true
      sensitiveHeaders:
    authentication:
      path: /authentication/**
      serviceId: authentication
      stripPrefix: true
      sensitiveHeaders:
